### PR TITLE
Functional Diagram

### PR DESCRIPTION
**Pull request by mcreixell**
Replace figM1 with new diagram and move sequence modeling diagram to supplemental figure 1.

### CODE REVIEW

**Comment by mcreixell** [comment]
DDMC_functional_diagram

**Review by aarmey — APPROVED** [review]
Great. Only one question—in what way is a regression model on the clusters "ad-hoc"?

**Comment by mcreixell** [comment]
Maybe it’s obvious but I meant that it’s not a fixed pipeline where automatically after clustering we apply PLSR for example. Instead, the regression model used should be the most suitable for the user’s purposes.

**Comment by aarmey** [comment]
Maybe just put "Modeling based on clusters" or some such?

**Comment by mcreixell** [comment]
Just an arrow from the motifs/centers box to the upstream kinase prediction box labeled as “modeling based on clusters”? So basically deleting the regression box?

**Comment by aarmey** [comment]
I think you can keep the regression box, just change the label.

**Comment by mcreixell** [comment]
@aarmey I’m not sure why this is failing, in my local all the tests pass in this branch.

**Comment by aarmey** [comment]
Should be fixed now.

**Comment by mcreixell** [comment]
Thanks!

**Pull request merged**
