### PR TITLE
Move pomegranate within repository

### PR DESCRIPTION
**Pull request by aarmey**

### CODE REVIEW

**Comment by aarmey** [comment]
@mcreixell this should be ready to merge. Please verify that you're seeing identical results first.

**Comment by aarmey** [comment]
After we merge this, I'll delete the separate repository I've been maintaining. Because of this, it will be important to merge these changes onto other branches.

**Comment by mcreixell** [comment]
The results are identical. Should I change the `.from_samples()` to DDMC with w=0 here?

**Comment by aarmey** [comment]
Great. We can do that after merging this.

**Pull request merged**
