### PR TITLE
Clustering of EBDT's MCF7 signaling

### PR DESCRIPTION
**Pull request by mcreixell**
@aarmey 

figureM6

I clustered the MCF7 signaling data of the Hijazi et al [paper](https://www.nature.com/articles/s41587-019-0391-9#Sec24) to see if our clusters could recapitulate some of their nodes / upstream kinase predictions. They have a data set in their supplementals ([DS3](https://www.nature.com/articles/s41587-019-0391-9#Sec24)) containing all K-S relationships generated from their phosphoproteomic analysis on HL60, NTERA2, and MCF7 cells. However, they don't specify what interaction was determined in what cell line... In the text they mention how many phosphosites were identified as putative downstream targets (PDTs) of specific kinases per cell line (MCF7 3,305; HL60 2,706; NTERA2 3,097) so ideally we would use only those relationships determined from MCF7 cells. Yesterday I reached out the corresponding author (Pedro Cutillas) asking for the data in Fig4A (#378) but he hasn't replied yet. 

Even so, I gave it a try with this K-S interaction data set by counting the number of PDTs per upstream kinase included in each cluster (see corresponding result for cluster 3 below). Unfortunately it looks like the same upstream kinases are enriched in all clusters. I think this might be because different kinases phosphorylate a different number of PDTs so more promiscuous kinases are more likely of ranking higher. Would it be reasonable to normalize each final kinase-PDT count per cluster to the total number of PDTs per upstream kinase inferred by them? For instance, if ERK1 has 1000 substrates in their data set and NEK3 20 and in cluster 3 we find 98 and 34 PDTs of each respectively. Could we just normalize by dividing 98/1000 and 34/20?

I'm not sure if I'm being clear please let me know if you have any questions. 

Screen Shot 2021-03-09 at 6 56 43 PM

### CODE REVIEW

**Comment by aarmey** [comment]
@mcreixell does the peptide clustering seem reasonable, ignoring the motifs?

**Comment by mcreixell** [comment]
There are a few interesting clusters but I'm not sure how to compare them to their results to validate them. They say that these cells are enriched by the PI3K-AKT-mTOR axis so I was thinking that maybe I could check if these kinases' PDTs are enriched in specific clusters?

**Comment by aarmey** [comment]
Have you ever taken a collection of known substrates, put them into a cluster artificially, and checked that you get the right kinase identification? If not this would be a fantastic test.

Isn't the point of using this dataset to verify cluster-kinase associations? In that case, shouldn't you just look at the activity of kinase-associated clusters with those drugs targeting that kinase? I'm not sure why comparing to the paper's conclusions helps...

**Comment by aarmey** [comment]
Last thought—there's no reason we couldn't try clustering in "fixed" mode, wherein we make clusters for each PSPL and keep the motif fixed during clustering.

**Comment by mcreixell** [comment]
Putting them into a cluster artificially would be just taking all these substrate's motifs, creating a PSSM and then checking the upstream kinase? I wonder if it would be helpful to also add these motifs to the MCF7 data set and check if by only using the sequence information we end up with a similar cluster.

**Comment by mcreixell** [comment]
I'm not sure I understand clustering in "fixed" mode.

**Comment by aarmey** [comment]
> Putting them into a cluster artificially would be just taking all these substrate's motifs, creating a PSSM and then checking the upstream kinase?

Yep.

> I wonder if it would be helpful to also add these motifs to the MCF7 data set and check if by only using the sequence information we end up with a similar cluster.

Not sure I follow what you mean.

**Comment by aarmey** [comment]
> I'm not sure I understand clustering in "fixed" mode.

Currently, the motif changes based on its members. "Fixed" mode would just use pre-defined motifs that don't change during EM.

**Comment by mcreixell** [comment]
> Not sure I follow what you mean.

I mean taking all the sequences of the MCF7 mass spec data set, adding a substantial number of new motifs for a known kinase, and then running DDMC observing only the sequences and not the data. This would test whether this method can extract a relevant motif that we know it's already there.

**Comment by mcreixell** [comment]
> Currently, the motif changes based on its members. "Fixed" mode would just use pre-defined motifs that don't change during EM.

How would we establish what centers have what pre-defined motifs? You said before a cluster per PSPL?

**Comment by aarmey** [comment]
The centers would still be fit.

**Comment by mcreixell** [comment]
Oh so the motif doesn't change during EM but we would still cluster peptides based on these pre-defined motifs so that the sequence score in each iteration would be the difference between each PSPL and a cluster's PSSM?

**Comment by aarmey** [comment]
> Oh so the motif doesn't change during EM but we would still cluster peptides based on these pre-defined motifs so that the sequence score in each iteration would be the distance between each *member peptide* and the cluster's PSSM?

Corrected here.

**Comment by mcreixell** [comment]
Sorry to keep asking but I'm having trouble understanding this. If the sequence distance is calculated between each member peptide and the cluster's PSSM, how do you use the pre-defined motifs during cluster assignment?

**Comment by mcreixell** [comment]
DDMC predicts AKT and CKII/PIM as upstream kinases of clusters 1 and 19, respectively and these seem to match up with the inhibition profiles of both clusters pretty well. Not sure what the best way of illustrating this would be. 

figM6

**Comment by aarmey** [comment]
For (D), have you tried a [stripplot](https://seaborn.pydata.org/generated/seaborn.stripplot.html) where cluster # is the x-axis and distance is the y-axis? You could then label the point that is a match. Think this would be compact and cleaner.

**Comment by mcreixell** [comment]
lI think it's a good idea, the only caveat is that the legend would contain all 60 kinases.

**Comment by aarmey** [comment]
No—don't bother labeling all the points, just the ones that are "hits".

**Comment by mcreixell** [comment]
@aarmey  Even if I label just the hits it can be tricky to avoid overlapping annotations:

Screen Shot 2021-04-06 at 11 40 28 AM

How about a ranked catplot showing the frobenius distance of a number of kinases?
Screen Shot 2021-04-06 at 11 48 29 AM

**Comment by mcreixell** [comment]
The only problem of a catplot is that it doesn't have an `ax` argument (it creates a figure object for its own) and I would have to overlay the plot as an `.svg` file. This is what I'm currently doing with clustermaps anyways so it wouldn't be too much of a problem.

**Comment by mcreixell** [comment]
@aarmey thoughts?

**Comment by aarmey** [comment]
I still feel like the stripplot is better, and we could just move the labels around manually at the end.

**Comment by mcreixell** [comment]
New edits:
- Upstream strip plot instead of heatmap, as discussed above.
- FigureM6—drug screening (see below). I tried to include more clusters but either there were no inhibitors matching our upstream kinase predictions or our predictions didn't match the drug screen consistently enough. The AKT motif of and overall signal of cluster 1 is really clear tho so I think this figure shows what we were looking for? Maybe the heatmap is not necessary? It looks a bit odd being just one row. To generate the bar plot showing substrate enrichment I've refined the PsP K-S interactions data to use only interactions that have been reported in vitro and in vivo.
- Removed motifs from all figures. I agree with the comment you made during my lab meeting that maybe including the motifs would be helpful for someone really interested in biochemistry but we care about the meaning of our clusters. I'm currently working on this.

I'll ask for your review once the checks pass. 

fig6

**Review by aarmey — APPROVED** [review]
Hmm... I might have more thoughts once I see how this fits into the manuscript. Looks fine for now.

**Pull request merged**
