### PR TITLE
Update for new version of pandoc

### PR DESCRIPTION
**Pull request by aarmey**
@mcreixell this should fix the manuscript build issues, but I'm seeing an issue with pandas indexing unrelated to this. Can you take a look?

### CODE REVIEW

**Comment by aarmey** [comment]
I'm going to revert the unrelated version changes just in case those did it.

**Comment by mcreixell** [comment]
I think this is breaking because manuscript build issues again?

**Comment by aarmey** [comment]
@mcreixell yep—still working on it.

**Comment by aarmey** [comment]
@mcreixell worked. Merging.

**Pull request merged**
