### PR TITLE
Correlating AXL, downstream substrates, and clusters

### PR DESCRIPTION
**Pull request by mcreixell**
@aarmey  These are the correlations of genes/proteins of interest and the phosphoproteomics clusters. Regarding the clusters, seems like there are 3 consistent groups; clusters 11, 19, and 23 on one hand, clusters 7, 16, 3, and 18 on the other, and then the rest. These trends are shown when looking at the selected genes of interest but also with 100 random genes (last plot). AXL correlates positively with the first group and negatively with the other two. It's interesting that at the RNA level, SRC, LYN, CLK2, YAP1, BLK, and INSR show either negative or very low positive correlation with clusters 11, 19, and 23 but increases in positive correlation at protein level.  

rna_corr

prot_corr

random_corr

### CODE REVIEW

**Comment by aarmey** [comment]
Interesting. Looks like there's a strong correlation structure in both datasets. This would suggest linking the two my PLSR may be more helpful than single correlations.

**Comment by mcreixell** [comment]
So using the RNA or protein expression data to predict cluster assignment?

**Comment by aarmey** [comment]
Maybe start with protein as it is more manageable in size...

**Comment by mcreixell** [comment]
Is this what we were thinking?

Screen Shot 2021-08-16 at 6 23 53 PM

**Comment by aarmey** [comment]
Need to look at R2X/Q2X first.

Also, are those scores/loadings on the bottom, or X/Y loadings?

**Comment by mcreixell** [comment]
scores (patients) left and X/Y loadings (proteins and clusters) right

**Comment by mcreixell** [comment]
Not very exciting... 

Screen Shot 2021-08-17 at 8 24 00 AM

**Comment by aarmey** [comment]
Hmm... yeah, maybe PLSR won't be so great...

Do 11, 19, 23 make sense as AXL correlates?

**Comment by mcreixell** [comment]
Tried a MultiTaskLasso model and seems to perform well (second image). The resulting weights include 125 proteins (shown in PCA below) but unfortunately AXL doesn't show up... 

PCA_LassoWeights

Screen Shot 2021-08-17 at 10 00 02 AM


Do you mean running PLSR with only clusters 11, 19, and 23?

**Comment by aarmey** [comment]
No, I just mean considering your univariate correlation results, discarding any more complicated model.

**Comment by mcreixell** [comment]
At first sight, I found pretty interesting that all 3 clusters that correlate with AXL have an enormous number of AHNAK (15, 50, and 70) and a handful of FLNA peptides (the two genes that correlated with AXL abundance and activation in the BioID analysis). I checked for the presence of these proteins in two random clusters and there were none. 

Further interesting molecules include the following below. I'm tried to be over-descriptive in case you recognize any proteins I'm not familiar with. Overall I think this is encouraging. 
- Cluster 11: PEAK1, SHP2, PAK4, FAK, and ~30 TNS1 peptides. TNS1 also widely detected in our MS AXL data and correlated with AXL activation. Also multiple CAV1 and CAVIN1&2 peptides which also think show up and cluster together in the in vitro data. 
- Cluster 19: activating ABL1 peptide, two AKT3, multiple ANXA2 peptides (also in in vitro data), one ATM, multiple CAVIN1&2, multiple DOCK, IL16, multiple LIMCH1, three MAP3K20 (or ZAK), three PAK2, multiple PDLIM2, 3 FAK, multiple SHANK3, multiple TJP1&2, multiple TLN1, ~50 TNS1 again (also TNS2 here).
- Cluster 23: CRK, GAS7?, multiple LIMCH1 again, activating ERK1&2, multiple PEAK1, PIK3R4, multiple SORBS1&3, multiple SPTB, multiple SORBS1&3, and again multiple SHANK3, TNS1-3 and TLN1.

**Comment by aarmey** [comment]
This all looks very reasonable.

**Pull request merged**
