### PR TITLE
add pickle test.

### PR DESCRIPTION
**Pull request by mcreixell**
Test added within `test_CoClustering.py`

### CODE REVIEW

**Comment by aarmey** [comment]
Try this out. It turns out both weren't really working... the reduce method needed to be in the Python classes. This test now passes, but I had to reorganize things a bit. Note that I changed it so that you shouldn't have to remove background before pickling, and the background rebuilds on unpickling. It's possible this creates a memory problem on unpickling, but it means that the class is fully capable on loading; you can even start fitting again. Let me know how it works and if you experience anything strange.

**Comment by mcreixell** [comment]
Thank you. I’m going to the lab now but will try this in a bit. How was PAM250 not working? It looked like I was able to access the centers after unpickling.

**Comment by aarmey** [comment]
That's true, but I think the values may have been wrong. I thought the arguments upon unpickling were passed to the parent class, but they were passed into the python child. They matched up just so where nothing errored, but the sequence contribution would have been set to the starting default of flat.

**Comment by mcreixell** [comment]
Okay both work smoothly now. And yes, it's great that the class is fully capable after loading! I'm merging this.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
