### PR TITLE
Add supps

### PR DESCRIPTION
**Pull request by mcreixell**
- Create supplemental figure S4 showing hypothesis testing and LR performance when using unclustered/k-means/GMM. 
- Remove NATs from figure4 and supplemental figure S5. 
- Add all supplemental figures to the manuscript.
- Add figure legends

### CODE REVIEW

**Comment by mcreixell** [comment]
@aarmey I'm trying to edit the `makefile` to a similar [format](https://github.com/meyer-lab/tHMM/blob/master/makefile) to what Farnaz has in her repository but I'm not getting the syntax right. Essentially I just would like to add figures using this:

```
flist = 1 2 3 S1 M2 M3 M4 M5 MS1 MS3 MS4
all: spell.txt $(patsubst %, output/%/manuscript/figure%.svg, $(flist))
```

and adding a `make output/%/manuscript` command to generate the pdf of the manuscript.

Could you please help me with this? I think this shouldn't be too far from the correct set up. Thanks.

**Comment by mcreixell** [comment]
This is the error I'm currently getting during the build.  

`Run make all
make: *** No rule to make target 'spell.txt', needed by 'all'.  Stop.
Error: Process completed with exit code 2.`

**Comment by aarmey** [comment]
Are you trying to add a certain feature? They're different formats in part because this repo has two papers in it.

**Comment by mcreixell** [comment]
One syntax change and one feature addition.

- Syntax change: Add figures by populating this list: `flist = 1 2 3 S1 M2 M3 M4 M5 MS1 MS3 MS4`
- Feature: Being able to generate a pdf of each manuscript. I saw that Farnaz' repo has this piece of code:
https://github.com/meyer-lab/tHMM/blob/07ba65f0fdbfd9b7c87be5895944a5fbf4f3d513/makefile#L32-L38

**Comment by aarmey** [comment]
Aha. I'll fix this on a new branch.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
