### PR TITLE
Pca rna

### PR DESCRIPTION
**Pull request by scottdtaylor95**

### CODE REVIEW

**Comment by mcreixell** [comment]
@aarmey do you think adding all these files could cause any issues or we're good to merge this?

**Comment by mcreixell** [comment]
Maybe in this case makes sense to only save the final merged file (keeping @scottdtaylor95's function around)?

**Comment by aarmey** [comment]
Yes, these would massively add to the repository size. It would be better to only include a merged file. Also, CSV reading/writing is quite slow and results in very large files. [A feather file would be better.](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#feather)

**Comment by mcreixell** [comment]
@aarmey Removed all RNAseq raw files and made a feather file with the merged data but this is too large. What would you advise?

Screen Shot 2021-11-22 at 12 00 19 PM

**Pull request closed without merging**
