### PR TITLE
Axl update

### PR DESCRIPTION
**Pull request by mcreixell**
You can find the updated analysis of the AXL data in the notebook. Before exporting I think it's worth discussing this on Monday. This PR includes:

- PSSM calculation includes the option of using all sequences or the PhosphoSitePlus as background. We find the ABL motif only when using the PsP background.
- Fixed upstream kinase prediction code.
- Added function to plot logos with `logomaker` 
- Show motifs for both models
- Run LASSO for both models

### CODE REVIEW

**Comment by mcreixell** [comment]
Not sure what the other two checks mean. Please let me know if there's anything I should do to take care of them.

**Comment by aarmey** [comment]
Oh you can ignore the codecov checks. They only pass with 90%+ coverage, which we shouldn’t worry about.

**Review by aarmey — APPROVED** [review]
This all looks great. Didn't you mention that a OLS or LASSO model worked better than PLSR? Given PLSR is also requiring more than two components, there's also not much interpretability benefit of using it. We can always just plot the weights for each cluster and phenotype from the OLS/LASSO model.

**Comment by aarmey** [comment]
Oh, never mind, I just saw you have that under PLSR. We can eventually get rid of the PLSR results in this case.

**Pull request merged**
