### PR TITLE
figureM3—Compare driver motifs across weights

### PR DESCRIPTION
**Pull request by mcreixell**
- Run binomial with weights 0, 15, 30, 50, 100, and 200 (failed to fit higher)
- Run PAM250 with weights 0, 3, 9, 15, 27, 35 (failed to fit higher)
- Fixed phosphoacceptor column of PSSMs to just normalize by frequency of pY, pT, or pS seen in a cluster, instead of normalizing by overall observed residue frequency in PhosphoSitePlus peptides. In that column we just care about what phosphoacceptor residue is enriched within a cluster. 

Looks like the motif we discussed last week (KRKpYW) shows up, regardless of what information source we prioritize or sequence distance method we use. However, we see variations. For instance cluster 8 and cluster 23 both seem to favor basic residues in the motifs NH2 terminus and have a strong preference for hydrophobic residues at +1. The motif of Cluster 23 is also clearly proline-enriched. Proteins containing WW domains, such as YAP, favor such motifs (being the consensus motif PPxY). I'm not aware whether protein kinases have WW domains as well. I find weird that the motif of Cluster 20 has two highly enriched adjacent tryptophan at positions +1 and +2 (as well as -1 and -2), I would assume this would cause a large steric hindrance that would prevent coupling. Maybe what this is indicating is that there are multiple peptides with W at +1 **or** +2 and/or W at -1 **or** -2.  

For now, I'm using the binomial model to generate the figures because it only needs 3 clusters whereas PAM250 needs many more (~6) to explain the difference between tumor and normal. Also, PAM250 fails to predict 4 samples and binomial predicts all them correctly. 

Next, I was planing to calculate the missingness error with these pickled models with variable weights to check if we still see a flat MSE line across weights or there are differences. Then I will keep working on figure 4. I think it works good enough with TP53 mutations but I'm not sure if we would be able to show the regression against EGFR mutant tumors with these prediction results? There are almost as many false positives (30) as correctly predicted positives (36). I will explore the clinical data set again to see if there are more molecular markers we could use. Then I'll update this figure with the motifs and upstream kinases applying the same design I'm using here in figure 3.

### CODE REVIEW

**Review by aarmey — APPROVED** [review]

**Comment by aarmey** [comment]
"...but I'm not sure if we would be able to show the regression against EGFR mutant tumors with these prediction results?" Do you mean it doesn't work with EGFRmut as the prediction? How about ALKmut? EGFR or ALK mut? I thought I remember some combination of these working?

**Comment by aarmey** [comment]
Everything else here looks good.

**Comment by mcreixell** [comment]
I’ve never checked the combination of multiple mutations. Do you mean assigning to 1 if it has an EGFR or ALK mutation? We were able to predict EGFR mutants with 15 clusters but not 24. However we make the argument in figure 2 that more clusters decreases the missingness error so that’s why I’m using 24 now. 

I’ll merge this and work on figure 4 in a new branch.

**Comment by aarmey** [comment]
What do you mean it predicted with one number of clusters and not the other? What were the AUC values on CV? It's important to distinguish a small change from some large change in model behavior.

**Comment by mcreixell** [comment]
Yes, exactly. With 15 clusters it looked like this:

image

**Comment by aarmey** [comment]
Yes, that's what I mean about combining ALK and EGFR.

Hmm... I don't think increasing the cluster number should have that much of an effect, because it should just be splitting clusters from the lower number. It could have something to do with how the logistic regression is setup, perhaps. I'd say go with the consistent story, and I can look at how the prediction is evaluated.

**Comment by mcreixell** [comment]
Ok, sounds good. I will check the combination and exhaust the options we have in predicting mutations with the binomial model I'm using in this figure.

**Pull request merged**
