### PR TITLE
A fixed motif distance class

### PR DESCRIPTION
**Pull request by aarmey**
This sets up a fixed motif class. It still requires implementation of a method, `motifLL`, that takes a peptide list and a PSPL, then returns the log-likelihood for each of the peptides in the list.

### CODE REVIEW

**Comment by mcreixell** [comment]
Could you please review to check that my edits are correct? It runs but the resulting cluster motifs look nothing like the corresponding PSPLs (see below). I also noticed the cluster motifs are not reproducible from run to run. 

Cluster motifs:
Screen Shot 2021-03-10 at 9 53 27 PM

Corresponding PSPLs:
Screen Shot 2021-03-10 at 9 53 39 PM

**Review by mcreixell — APPROVED** [review]

**Comment by aarmey** [comment]
There's no reason to expect the PSSMs to look just like the PSPLs, because you aren't feeding in a set of random sequences.

Do you mean the PSSMs are different from run-to-run, or the PSPLs?

I'm making some other edits right now.

**Comment by aarmey** [comment]
Ok, I think this is working and I've added tests for the new class. Merging.

**Comment by mcreixell** [comment]
> Do you mean the PSSMs are different from run-to-run, or the PSPLs?

The PSSMs

**Pull request merged**
