### PR TITLE
Update Imputation Figure

### PR DESCRIPTION
**Pull request by mcreixell**
- Smooth out phenotype prediction errors
- Updated missingness diagram
- Imputation figure, currently place as figureM2 although still not sure since the results are not ideal:

image

I think ideally we would see a clearer improvement in missingness imputation with a mixed weight but it barely seems to vary (F). However, there seems to be a slight increase at higher percentage levels compared to weight 0 or 40 (G-I). In terms of cluster selection, I think showing only B does the job. All in all, I think this figure still underscores a key benefit of the model which is modeling missingness and justifies our hyerparameter selection so I would be inclined towards including it as a main figure but I'm not sure. I think I would just include A,B, F-I. What do you think?

### CODE REVIEW

**Comment by mcreixell** [comment]
The large number of line additions is coming from the files containing the MSE.

**Review by aarmey — APPROVED** [review]
I think this works.

A Lowess fit would be better than a linear one in summarizing the error. I think that's just an option in seaborn.

**Comment by mcreixell** [comment]
These fits look much cleaner now, thanks. Is PCA typically a robust method to infer missingness? Is being close to PCA's imputation performance a good sign?

image

**Comment by aarmey** [comment]
Yep—not surprising that PCA does well. How do you decide the number of components to use?

**Comment by mcreixell** [comment]
I'm using 5 which is how many we were using to initialize DDMC with k-means. Should I check if with a larger number of components it performs much better?

**Comment by aarmey** [comment]
Larger and smaller. You don't have to make a figure showing it.

**Pull request merged**
