### PR TITLE
Update Results Text

### PR DESCRIPTION
**Pull request by mcreixell**
This includes updated text for figures:
- M1 
- M3
- M4
- Captions of all supplemental figures

I re-organized the supplemental figures to show the comparison between the ROC plots of the different lasso models I presented last week (STK11 and EGFRm/ALKf, see below). I'm currently including this in supplemental figure 5. In the case of STK11 DDMC seems consistently better than k-means and GMM. The performance of unclustered is always great to my surprise. All these regression strategies struggle more with EGFRm/ALKf. DDMC doesn't seem to do much better than GMM but we can still argue that we're using the entire data set whereas the rest of the strategies use only complete portions (~1.311 vs ~30.561 peptides). 

image

### CODE REVIEW

**Comment by mcreixell** [comment]
On PhosphoSitePlus I found a very rich data set with experimentally-validated Kinase-Substrate interactions that I uploaded into this branch. I was wondering what would be the best way for us to use it. I think that maybe we could:

1. Extract the PSSM of all validated substrates for a particular upstream kinase and check if it matches with the corresponding cluster PSSM our model predicts is modulating. Could this serve as a computational validation of our Kinase-cluster motif prediction?
2. Explore how many / what proteins within each cluster an upstream kinases has been shown to phosphorylate experimentally. This could help us gain insights into the mechanisms.

**Comment by aarmey** [comment]
Do you have a reference or page that describes the data?

**Review by aarmey — APPROVED** [review]

**Comment by mcreixell** [comment]
Kinase-substrate dataset: experimentally determined substrates, sequences, cognate kinases, and metadata curated from the literature

https://www.phosphosite.org/staticDownloads.action

**Comment by aarmey** [comment]
This link doesn't work for me...

**Comment by mcreixell** [comment]
phosphosite.org —> Downloads —> from PsP. If you want to download data you have to create an account but without creating one you should be able to read the description of the file.

**Comment by mcreixell** [comment]
I attached the data here: https://github.com/meyer-lab/resistance-MS/discussions/343

**Pull request merged**
