### PR TITLE
Fig m5

### PR DESCRIPTION
**Pull request by mcreixell**
The regression models (logistic and SVC) don't seem to work well at predicting clinical stage. Even when converting this to a binary problem (early—phaseI-IIA— vs late stage—phaseIIA+). I tried using both 15 or 20 clusters and PAM250 or Binomial.

### CODE REVIEW

**Review by aarmey — COMMENTED** [review]
Why does the ROC curve have 7 distinct steps?

**Comment by mcreixell** [comment]
To what plot are you referring to? I'm not sure if this answers your question but I always set the number of CV folds to the number of clusters.

**Comment by aarmey** [comment]
Screen Shot 2020-10-30 at 1 54 18 PM

Also, why would the number of clusters have anything to do with the number of CV folds?

**Comment by mcreixell** [comment]
I decreased the number of folds to 4 which yields ROC plots with ~20 steps.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
