### PR TITLE
FigureM2 update

### PR DESCRIPTION
**Pull request by mcreixell**
Increased number of TMT removed to 5 (1 per iteration) and checked different number of clusters and different weights. Looks like now data only and mix perform very similarly unfortunately... Also, there must be something off in the way I'm calculating the MSE across weights (last plot) because there is a very clear difference between Data only and Mix versus Sequence—which imputes missingness worse. However, as you can se in the last plot, the MSE is a flat line across weights... I tried fitting a new model every time, and pickling and re-fitting the Data only, Mix, and Seq only models and all show this flat line.

Also, I added the missingness diagram `.svg` file to the `figures` folder, I was trying to add it to the first spot but I'm not sure how.

### CODE REVIEW

**Comment by mcreixell** [comment]
(The number of additions is so big because of the MSE files I stored.)

**Review by aarmey — CHANGES_REQUESTED** [review]
Try looking at the geometric mean of the squared error. Your MSE value is likely only reflecting those few points with high error, while your vs. missingness plots are log-scaled on y.

**Comment by mcreixell** [comment]
Ok. The geometric mean of the **linear** mean squared errors?

**Comment by aarmey** [comment]
Yes.

**Comment by mcreixell** [comment]
The trend seems to remain the same. I think it's concerning that we do see this difference between the Data/Mix vs Seq only and not when checking across different weights, but maybe figuring this out is not really worth the time? The first 3 plots already evaluates the imputation error in the three cases we care about so maybe we could just ignore the last plot for now and move forward. @aarmey

**Review by aarmey — APPROVED** [review]

**Pull request merged**
