### PR TITLE
BioID PCA

### PR DESCRIPTION
**Pull request by mcreixell**
BioID plot with SEM instead of Stdev and after log transforming. Interesting that AF154 makes 821 more negative and 750 more positive across PC2. Not sure how to interpret the controls. 

BioID

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
You probably need more filtering out of junk from the dataset. For example, maybe there must be at least a 10-fold increase over the negative controls. I see quite a few proteins included that are probably just background, and that could easily drown out the signal. Another approach would be to start with a plot of just known interactors.

**Comment by mcreixell** [comment]
So I filtered any proteins out that did not show a count of at least 7 and/or those that do not show an increase of at least 3x across any of the conditions. This results in a collection of 26 genes (see below). 

BioID

**Comment by aarmey** [comment]
FLNA and AHNK should absolutely show up too—almost no peptides in the controls, 30+ in all the positive samples.

**Comment by mcreixell** [comment]
There was a problem in the way I was filtering based on fold-change increase. I think this makes sense now. However, it seems like all the AXL interactors in the presence of AF154 are clustered together (FLNA, AHNK, AXL, CTTN/SRC8, EGFR...). 

BioID
Screen Shot 2021-08-12 at 9 41 15 AM

**Comment by aarmey** [comment]
Maybe try without log-transforming? There's not a huge difference in scale here that necessitates it. You could also look at the separation with NNMF.

The results here make a lot of sense already. By far the biggest difference is w.r.t. the controls, and then PC2 is the effect of AF154. Some of the proteins positive on PC2 are related to ER sorting which we'd expect.

**Comment by mcreixell** [comment]
What plots do you generate with NNMF? Like [this](https://scikit-learn.org/stable/auto_examples/applications/plot_topics_extraction_with_nmf_lda.html#sphx-glr-auto-examples-applications-plot-topics-extraction-with-nmf-lda-py) where each topic would be condition and each item in the bar plot a gene?

**Comment by aarmey** [comment]
You can plot it exactly the same (only the nomenclature is different). `transform()` gives you the "scores". `X.components_` gives you the "loadings".

**Comment by mcreixell** [comment]
This is with NMF. Scores look pretty much identical but now the AXL interactors correlate closer with Bio/Dox controls. As expected all the weights are positive, is this okay or usually these are somehow normalized after fitting?

NMF

**Comment by mcreixell** [comment]
Yeah I forgot I was scaling the data for PCA inside my pca function. This looks much better. 

NMF

**Comment by aarmey** [comment]
Beautiful!!

**Pull request merged**
