### PR TITLE
Plot Luminex Dasatinib DR—p-YAP, p-ABL, p-SRC

### PR DESCRIPTION
**Pull request by mcreixell**
@aarmey @scottdtaylor95 

Observations:
- Dose response effect in p-YAP signal with KO cells but not WT. Not a perfect curve (signal in 40nM bigger than 8nM and 1000nM bigger than 200nM) however.
- Low number of ABL beads detected. This is surprising given that we calculated the number of beads to add with this kit based on our p-YAP coupling experiment since we used the ABL kit as a control and we had data to calculate this. 
- High number of p-SRC, but no signal detected which would be foreseeable in dasatinib-treated cells but the control (0nM) doesn't show any either.
- Is the varying number of YAP and ABL beads per sample concerning or some variation is expectable?

Bead Counts:
[counts.pdf](https://github.com/meyer-lab/resistance-MS/files/5861714/counts.pdf)

Average Net MFI:
[MFI.pdf](https://github.com/meyer-lab/resistance-MS/files/5861713/MFI.pdf)

### CODE REVIEW

**Comment by aarmey** [comment]
Can we meet and talk about this tomorrow? Overall this looks promising.

**Comment by mcreixell** [comment]
Sure! Would around 1pm work? We’re lysing tomorrow so I think anywhere between 1-3pm should work with us.

**Comment by mcreixell** [comment]
Nvm just scheduled 1:30p via calendly!

**Comment by mcreixell** [comment]
@aarmey @scottdtaylor95 

Counts:
Counts_BR2

Median. In this case, I couldn't use the MFI because something was off with the signal of the background versus the actual samples. 
Median_BR2

**Comment by aarmey** [comment]
What is the lysis buffer here, and it's final dilution in the assay (on average)?

**Comment by scottdtaylor95** [comment]
The background wells were filled with 16uL of 1% BSA PBS as a blank instead of lysate, all other steps were identical

**Comment by aarmey** [comment]
My other question is how these raw MFI's (without background subtraction) compare to those in the previous experiment. Is the bg the same but the samples are lower? It's possible we have to dilute out more of the lysis buffer for the pulldown to work...

**Comment by scottdtaylor95** [comment]
Background for ABL is similar to the first pass, about double here on the second pass for SRC and YAP vs first pass. Not sure if we added a lysate blank to the background wells, and if so whether it was the PBS or RIPA. The lysate amount for the first pass was much lower - maybe 1-2ug, in about the same volume (16uL/well). Probably larger dilutions for more concentrated samples (1-4, 7-10) in that run.

**Comment by aarmey** [comment]
Huh... honestly I'm not sure what to think. My only thought is trying a 1:10 dilution of the lysates to reduce the amount of detergent around.

What's off with the MFI?

**Comment by scottdtaylor95** [comment]
I'm not sure what you mean? What do you mean what's off?

**Comment by aarmey** [comment]
Marc: "In this case, I couldn't use the MFI because something was off with the signal of the background versus the actual samples."

**Comment by mcreixell** [comment]
I was referring to what Scott just said on Slack: "It's due to the very high background. It averages the median value in the background wells and subtracts it".

This what the Median of the first experiment looks like:

Screen Shot 2021-02-02 at 4 02 37 PM

**Comment by aarmey** [comment]
So the median is higher in the previous experiment, and was higher in the more dilute samples of that experiment. I think that supports trying with more dilute samples.

**Comment by mcreixell** [comment]
This is the case for YAP and ABL but not SRC I think. We more or less see a decreasing trend in the median (~80 to 20) in SRC in the second experiment whereas the median in the first run looked completely flat and low (~20). In this second experiment Scott decreased the number of SRC beads per well. Could this also have affect the assay?

**Comment by scottdtaylor95** [comment]
Another note, I read this on the thermo amine notes - "Low concentrations of sodium azide (≤ 3 mM or 0.02%) or thimerosal (≤ 0.02 mM or 0.01%) generally do not significantly interfere with NHS-ester reactions, but higher concentrations do interfere." While our pulldown antibody was in .02% azide before coupling, our detection antibody for pYAP y357 had .097% azide. Don't know if this may have prevented biotinylation.

**Comment by aarmey** [comment]
Hmm... that's possible. We'd have to do a streptavidin pull-down to confirm coupling. That wouldn't influence the Bird assays, though.

It could be good to add in something like Mek or Erk that absolutely should have a strong signal.

**Comment by mcreixell** [comment]
Experiment 3:

Counts:
Exp3_Counts


Signal:
Exp3_Median

**Comment by aarmey** [comment]
My thoughts on this are:

1. A bead set that definitely should give signal (like Mek / Erk) would still be helpful.
2. It would also be helpful to run the same lysates in a western so we know what the Yap signal should look like.
3. You can run different lysate dilutions in the same Luminex experiment. That would make it easier to determine how this affects the sensitivity of the assay.

**Comment by mcreixell** [comment]
a

b

**Comment by mcreixell** [comment]
background:

a

**Comment by scottdtaylor95** [comment]
Median Signal:
Screenshot (289)

**Comment by scottdtaylor95** [comment]
Background:
Screenshot (290)

**Comment by mcreixell** [comment]
This is ready to merge after passing the checks. I deleted all the obsolete / troubleshooting data and kept the final two experiments with the working assay showing the Das pABL/pSRC/pYAP dose response.

**Pull request merged**
