### PR TITLE
delete Tregs and format figM5.

### PR DESCRIPTION
**Pull request by mcreixell**
Before I forgot to drop Tregs.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Why delete Tregs?

**Comment by mcreixell** [comment]
because the coefficients of all cell types have the same sign in each cluster and I would expect Tregs to be the opposite of T-cells. I’m not sure how to explain this result if we keep them.

**Comment by aarmey** [comment]
This is because the largest variation is simply the degree of immune infiltration, so the CD8 and Treg numbers are correlated. People often talk about the Treg:CD8 ratio because it normalizes this out, not because the two cell types are anti-correlated. I can help to explain this in the text.

**Comment by mcreixell** [comment]
I would still merge this since there are a couple minor format edits I'd like to include into this figure.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
