### PR TITLE
Axl new clusters

### PR DESCRIPTION
**Pull request by mcreixell**
- Fix MassSpecClustering methods
- Generate new clusters with PAM250 
- Generate new clusters with Binomial

### CODE REVIEW

**Comment by mcreixell** [comment]
This looks much much better. As you predicted, all values are within the expected range, except from very large negative numbers that I've limited to -4.0. Also, all the non-phosphorylatable residues at the central position where -inf so I'm setting them to 0. That way we can include this position in the logo plot and see if it's a tyrosine or serine/threonine cluster. Lastly, as you can see below there is clearly a W depletion. So I think we should somehow normalize to the global AA frequency among MS peptides. @aarmey 

Screen Shot 2020-10-06 at 10 26 26 AM

**Comment by aarmey** [comment]
You could calculate the PSPL for the entire dataset (without the scores weighting) and then take the difference?

**Comment by mcreixell** [comment]
Do you mean generating a frequences matrix of all sequences in the data set using biopython:

https://github.com/meyer-lab/resistance-MS/blob/b38fe03cf450523a9ca509827b15f2a3a7cc9e2b/msresist/binomial.py#L39-L46

and then log2-transforming? As you can see `position_weight_matrix ` uses the natural `AAfreq` for pseudocounts. Maybe we could set `pseudcounts=0.5` for instance, since we're interested in the frequencies present in the data set?

**Comment by aarmey** [comment]
You could just use your function with all the scores set to 1.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
