### PR TITLE
Build docx

### PR DESCRIPTION
**Pull request by aarmey**
This adds a Word docx to the build. Note that the figures won't show up in this document. For a PDF, the best strategy is to go to the built webpage, and then export or print to PDF in the web browser.

### CODE REVIEW

**Review by mcreixell — APPROVED** [review]

**Comment by mcreixell** [comment]
Great, thanks! Is this the build website? 

https://github.com/meyer-lab/resistance-MS/runs/1602013454?check_suite_focus=true 

I can't a find an option to print or export to PDF. Sorry I remember you showed how to do this in a lab meeting.

**Comment by aarmey** [comment]
https://meyer-lab.github.io/resistance-MS/method/manuscript.html

**Comment by mcreixell** [comment]
Isn't this always the manuscript version that is in master? What I'd find useful is being able to see how the manuscript would look like in a specific branch.

**Comment by aarmey** [comment]
Hmm... you should be able to see the docx and figure files at the link you provided. You're right, there isn't a way to get a PDF of another branch at the moment.

**Comment by mcreixell** [comment]
Ok! This works, thanks!

**Pull request merged**
