### PR TITLE
MS6-Compare predictions with varying weights

### PR DESCRIPTION
**Pull request by mcreixell**
I think this looks good enough to claim that sequence information helps improve model prediction? In all three cases looks like w=0 works worse. I re-made this figure and these AUC values are consistent.

preds

### CODE REVIEW

**Review by aarmey — APPROVED** [review]
Yep. We should be able to find a consistent trend w.r.t. weights versus ROC, so I'd want to make sure this isn't just random fluctuation based on starting points.

By the way, there's absolutely no purpose for an ROC curve to have the individual folds indicated. You should just get rid of those lines.

**Comment by aarmey** [comment]
Also, the ROC uncertainty band should be SEM, not stdev.

**Comment by mcreixell** [comment]
Would running each ROC plot multiple times and showing the mean and SEM of the resulting AUC means a way of demonstrating consistency in this trend w.r.t weights?

**Comment by aarmey** [comment]
Are you re-running the GMM in that strategy? If not, you won't capture the main source of variance.

Either way I don't think it's worth doing something this complicated. I'd just re-generate the GMM results once or twice and make sure you're generally getting the same conclusion.

**Comment by mcreixell** [comment]
Yes, I was doing this but it's getting complicated so I think I will leave it like this for now. I run this a few times and these trends look very reproducible: 

m2

**Pull request merged**
